-- Phase 3 - Step 1
-- Prepare MES raw tables in Snowflake.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SMARTFACTORY_DB;
USE SCHEMA RAW_DATA;

CREATE TABLE IF NOT EXISTS MACHINE_STATUS_RAW (
    MACHINE_ID VARCHAR,
    STATUS VARCHAR,
    LAST_UPDATED TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS WORK_ORDERS_RAW (
    ORDER_ID VARCHAR,
    MACHINE_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    TARGET_QUANTITY NUMBER,
    ORDER_STATUS VARCHAR,
    CREATED_AT TIMESTAMP_NTZ
);

-- Quick verification
SHOW TABLES LIKE 'MACHINE_STATUS_RAW' IN SCHEMA SMARTFACTORY_DB.RAW_DATA;
SHOW TABLES LIKE 'WORK_ORDERS_RAW' IN SCHEMA SMARTFACTORY_DB.RAW_DATA;
